version: '3.8'

services:

  umweltrechner:
    build: ./umweltrechner
    image: umweltrechno
    container_name: umweltrechner
    depends_on:
      - mysql
      - postgres
      - keycloak
    ports:
      - "8230:8230"
    networks:
      - umweltrechner
    environment:
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3312/umweltrechner

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3312:3312"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: umweltrechner
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3312
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - umweltrechner

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - umweltrechner

  keycloak:
    build:
      context: ./keycloak
      dockerfile: keycloak/Dockerfile.local
    container_name: keycloak
    depends_on:
      - postgres
    environment:
      - KEYCLOAK_ADMIN=keycloak
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_LOG_LEVEL=INFO
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    networks:
      - umweltrechner

networks:
  umweltrechner:

volumes:
  postgres_data:
    driver: local