version: '3.8'

services:

  umweltrechner:
    build: ../umweltrechner
    image: umweltrechno
    container_name: umweltrechner
    depends_on:
      - umweltrechner-mysql-db
      - umweltrechner-backend-keycloak-mysql
      - keycloak
    ports:
      - "8230:8230"
    networks:
      - umweltrechner
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://umweltrechner-mysql-db:3312/umweltrechner

  umweltrechner-mysql-db:
    image: mysql:8.0
    container_name: umweltrechner-mysql-db-server
    ports:
      - "3312:3312"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: umweltrechner
      MYSQL_PASSWORD: 123456Aa@
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3312
    volumes:
      - ./../umweltrechner-docker/scripts:/docker-entrypoint-initdb.d/
      - ./../umweltrechner-docker/mysql:/var/lib/mysql
    networks:
      - umweltrechner

  umweltrechner-backend-keycloak-mysql:
    image: mysql:8.0
    container_name: umweltrechner-keycloak-backend-mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - ./../umweltrechner-keycloak-docker/mysql:/var/lib/mysql
    ports:
      - "3320:3320"
    networks:
      - umweltrechner

  keycloak:
    image: jboss/keycloak
    container_name: umweltrechner-keycloak-umweltrechner-server
    depends_on:
      - umweltrechner-backend-keycloak-mysql
    restart: unless-stopped
    environment:
      KEYCLOAK_FRONTEND_URL: https://keycloak.sensorguard.systems/auth
      DB_VENDOR: MYSQL
      DB_ADDR: umweltrechner-backend-keycloak-mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: develop
      KEYCLOAK_PASSWORD: develop
      PROXY_ADDRESS_FORWARDING: true
      REDIRECT_SOCKET: "proxy-https"
    ports:
      - "8080:8080"
    volumes:
      - ./../umweltrechner-keycloak/export-prod:/tmp/export/
    command:
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.dir=/tmp/export/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    networks:
      - umweltrechner

networks:
  umweltrechner:
